### ISSUE TITLE
mathjax does not render properly in a PDF

### ISSUE THREAD

**Issue by karimsa** [GitbookIO/gitbook#646]
I understand that #36 has been resolved, and the relatively new mathjax plugin inside of GitBook is very useful. So hats off to that.

However, it seems that there is an issue with rendering the actual mathjax when GitBook generates its PDFs - all the mathjax seems to be fully omitted during generation.

Thanks.

**Comment by AaronO** [comment]
@karimsa This is fixed in the `2.0.0` release which is in `beta` right now. The `1.5.x` releases didn't support rendering `mathjax` for ebooks (PDF, ePUB, Mobi, ...)

You can use the beta by going to your book's build settings and selecting it.

**Comment by karimsa** [comment]
@AaronO I am using the `2.x.x beta` builder for my book, but it still does not render mathjax for the PDF.
